### ISSUE TITLE
Check spelling

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap-restapi#8]
### Page URL

https://docs.netapp.com/us-en/ontap-restapi/ontap/post-storage-volumes.html

### Page title

Create a volume on an SVM and storage aggregates

### Summary

I spotted "gaurantee". Could be other mispellings.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thank you @jfsinmsp for highlighting this.

**Comment by netapp-ranuk** [comment]
Hi @jfsinmsp 

The spelling error has been fixed on the doc site. https://docs.netapp.com/us-en/ontap-restapi/ontap/post-storage-volumes.html

Thank you!
